apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager-local-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - alertmanager.homelab.local
    secretName: homelab-local-tls
  rules:
  - host: alertmanager.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-kube-prometheus-alertmanager
            port:
              number: 9093
