apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-public-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - grafana.spencer-kennedy.com
    secretName: homelab-tls
  rules:
  - host: grafana.spencer-kennedy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 80