apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: neo4j
  namespace: neo4j
  labels:
    app: neo4j
    app.kubernetes.io/part-of: spencer-os
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`neo4j.homelab.local`)
      kind: Rule
      services:
        - name: neo4j
          port: 7474
  tls:
    secretName: homelab-local-tls
