apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-public
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure

spec:
  tls:
  - hosts:
    - spencer-kennedy.com
  rules:
  - host: spencer-kennedy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio
            port:
              number: 80