apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: npckennedy/portfolio:029419cc277eee48ebe135be9e30f944694f3a4f
        ports:
        - containerPort: 5000